import { MigrationInterface, QueryRunner } from "typeorm";

export class CreatePanelTables1765599328680 implements MigrationInterface {
    name = 'CreatePanelTables1765599328680'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "apertura_llc_requests" ("request_id" integer NOT NULL, "current_step_number" integer NOT NULL, "llc_name" character varying(255), "business_type" character varying(255), "business_description" text, "llc_phone_number" character varying(50), "llc_website" character varying(500), "llc_email" character varying(255), "incorporation_state" character varying(100), "incorporation_date" date, "has_ein" boolean, "ein_number" character varying(50), "ein_document_url" text, "no_ein_reason" text, "certificate_of_formation_url" text, "registered_agent_address" jsonb, "registered_agent_name" character varying(255), "registered_agent_email" character varying(255), "registered_agent_phone" character varying(50), "registered_agent_type" character varying(20), "needs_bank_verification_help" boolean, "bank_account_type" character varying(50), "bank_name" character varying(255), "bank_account_number" character varying(100), "bank_routing_number" character varying(100), "bank_statement_url" text, "owner_nationality" character varying(100), "owner_country_of_residence" character varying(100), "owner_personal_address" jsonb, "owner_phone_number" character varying(50), "owner_email" character varying(255), "llc_type" character varying(20), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fe835abf385aade7c256ebcdc4c" PRIMARY KEY ("request_id"))`);
        await queryRunner.query(`CREATE TABLE "renovacion_llc_requests" ("request_id" integer NOT NULL, "current_step_number" integer NOT NULL, "llc_name" character varying(255), "society_type" character varying(255), "registration_number" character varying(100), "state" character varying(100), "has_data_or_directors_changes" boolean, "physical_address" character varying(500), "correspondence_address" character varying(500), "country" character varying(100), "city" character varying(100), "postal_code" character varying(20), "main_activity_description" text, "contact_phone" character varying(50), "contact_email" character varying(255), "has_ein" boolean, "ein_number" character varying(50), "main_activity" text, "responsible_person" jsonb, "wants_registered_agent" boolean, "registered_agent_info" jsonb, "identity_document_url" text, "proof_of_address_url" text, "llc_contract_or_operating_agreement_url" text, "articles_of_incorporation_url" text, "registered_address" character varying(500), "registered_country" character varying(100), "registered_state" character varying(100), "registered_city" character varying(100), "registered_postal_code" character varying(20), "capital_contributions_url" text, "state_registration_url" text, "certificate_of_good_standing_url" text, "data_is_correct" boolean, "observations" text, "payment_method" character varying(100), "amount_to_pay" numeric(10,2), "wants_invoice" boolean, "payment_proof_url" text, "llc_type" character varying(20), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_158d12602ae023c7b33054fb54f" PRIMARY KEY ("request_id"))`);
        await queryRunner.query(`CREATE TABLE "cuenta_bancaria_requests" ("request_id" integer NOT NULL, "current_step_number" integer NOT NULL, "applicant_email" character varying(255), "applicant_first_name" character varying(255), "applicant_paternal_last_name" character varying(255), "applicant_maternal_last_name" character varying(255), "applicant_phone" character varying(50), "account_type" character varying(50), "business_type" character varying(255), "legal_business_identifier" character varying(255), "industry" character varying(255), "economic_activity" text, "ein" character varying(50), "certificate_of_constitution_or_articles_url" text, "operating_agreement_url" text, "company_address" jsonb, "is_registered_agent_in_usa" boolean, "registered_agent_name" character varying(255), "registered_agent_address" text, "bank_name" character varying(255), "swift_bic_aba" character varying(50), "account_number" character varying(100), "bank_account_type" character varying(50), "first_registration_date" date, "has_litigated_current_fiscal_year" boolean, "litigation_details" text, "is_same_address_as_business" boolean, "owner_personal_address" jsonb, "proof_of_address_url" text, "llc_type" character varying(20), "document_certification" text, "accepts_terms_and_conditions" boolean, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8fbbb57920b39f72929d57e88cc" PRIMARY KEY ("request_id"))`);
        await queryRunner.query(`CREATE TABLE "requests" ("id" SERIAL NOT NULL, "type" character varying(50) NOT NULL, "status" character varying(50) NOT NULL, "client_id" integer NOT NULL, "partner_id" integer, "notes" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0428f484e96f9e6a55955f29b5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "members" ("id" SERIAL NOT NULL, "request_id" integer NOT NULL, "first_name" character varying(255) NOT NULL, "last_name" character varying(255) NOT NULL, "passport_number" character varying(100) NOT NULL, "nationality" character varying(100) NOT NULL, "scanned_passport_url" text, "date_of_birth" date NOT NULL, "email" character varying(255) NOT NULL, "phone_number" character varying(50) NOT NULL, "member_address" jsonb NOT NULL, "percentage_of_participation" numeric(5,2) NOT NULL, "validates_bank_account" boolean NOT NULL DEFAULT false, "additional_bank_docs_url" text, "ssn_or_itin" character varying(50), "national_tax_id" character varying(100), "tax_filing_country" character varying(100), "owner_contributions_2024" numeric(12,2), "owner_loans_to_llc_2024" numeric(12,2), "loans_reimbursed_by_llc_2024" numeric(12,2), "profit_distributions_2024" numeric(12,2), "spent_more_than_31_days_in_us" character varying(50), "has_us_financial_investments" character varying(50), "is_us_citizen" character varying(50), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_28b53062261b996d9c99fa12404" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bank_account_validators" ("id" SERIAL NOT NULL, "request_id" integer NOT NULL, "first_name" character varying(255) NOT NULL, "last_name" character varying(255) NOT NULL, "date_of_birth" date NOT NULL, "nationality" character varying(100) NOT NULL, "citizenship" character varying(100) NOT NULL, "passport_number" character varying(100) NOT NULL, "scanned_passport_url" text NOT NULL, "work_email" character varying(255) NOT NULL, "use_email_for_relay_login" boolean NOT NULL DEFAULT false, "phone" character varying(50) NOT NULL, "can_receive_sms" boolean NOT NULL DEFAULT false, "is_us_resident" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_0e50563ece8cfec65958af9704b" UNIQUE ("request_id"), CONSTRAINT "REL_0e50563ece8cfec65958af9704" UNIQUE ("request_id"), CONSTRAINT "PK_a8ed238098edb4e9094d81ea1ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bank_account_owners" ("id" SERIAL NOT NULL, "request_id" integer NOT NULL, "first_name" character varying(255) NOT NULL, "paternal_last_name" character varying(255) NOT NULL, "maternal_last_name" character varying(255) NOT NULL, "date_of_birth" date NOT NULL, "nationality" character varying(100) NOT NULL, "passport_or_national_id" character varying(100) NOT NULL, "identity_document_url" text NOT NULL, "facial_photograph_url" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5e7316e8787cd13918aa24df553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "process_steps" ("id" SERIAL NOT NULL, "request_id" integer NOT NULL, "name" character varying(255) NOT NULL, "description" text, "status" character varying(50) NOT NULL, "order_number" integer NOT NULL, "completed_at" TIMESTAMP WITH TIME ZONE, "completed_by" character varying(255), "assigned_to" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8364ae09123f5e55ae040504e52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" SERIAL NOT NULL, "request_id" integer NOT NULL, "field_name" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "type" character varying(50) NOT NULL, "zoho_workdrive_file_id" character varying(255) NOT NULL, "zoho_workdrive_url" text NOT NULL, "size" bigint NOT NULL, "mime_type" character varying(100), "description" text, "uploaded_by" integer NOT NULL, "uploaded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "type" character varying(50) NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "read" boolean NOT NULL DEFAULT false, "link" character varying(500), "request_id" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_preferences" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "language" character varying(10) NOT NULL DEFAULT 'es', "theme" character varying(20) NOT NULL DEFAULT 'light', "timezone" character varying(100) NOT NULL DEFAULT 'America/Mexico_City', "notifications" jsonb NOT NULL DEFAULT '{"email": true, "push": true, "requestUpdates": true, "documentUploads": true}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_458057fa75b66e68a275647da2e" UNIQUE ("user_id"), CONSTRAINT "REL_458057fa75b66e68a275647da2" UNIQUE ("user_id"), CONSTRAINT "PK_e8cfb5b31af61cd363a6b6d7c25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "process_config" ("id" SERIAL NOT NULL, "auto_advance_steps" boolean NOT NULL DEFAULT false, "require_approval" boolean NOT NULL DEFAULT true, "default_assignee" character varying(255), "notification_delay" integer NOT NULL DEFAULT '24', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_939f4f0fe8ad33a33f5ff10cfd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "company" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "type" character varying(20) NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" ADD CONSTRAINT "FK_fe835abf385aade7c256ebcdc4c" FOREIGN KEY ("request_id") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD CONSTRAINT "FK_158d12602ae023c7b33054fb54f" FOREIGN KEY ("request_id") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD CONSTRAINT "FK_8fbbb57920b39f72929d57e88cc" FOREIGN KEY ("request_id") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_e336e481a84734861089a92a233" FOREIGN KEY ("client_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_0d449eefabbcd1dcfcda92e188e" FOREIGN KEY ("partner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_d6c6be79cf7ccbbbe9bee93e91f" FOREIGN KEY ("request_id") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_account_validators" ADD CONSTRAINT "FK_0e50563ece8cfec65958af9704b" FOREIGN KEY ("request_id") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_account_owners" ADD CONSTRAINT "FK_baa295509b3588f4464c092b9c1" FOREIGN KEY ("request_id") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "process_steps" ADD CONSTRAINT "FK_a26849bc9154027c9600ca9aff5" FOREIGN KEY ("request_id") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_640ed9849e6eb66177436f91f50" FOREIGN KEY ("request_id") REFERENCES "requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_b9e28779ec77ff2223e2da41f6d" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_405532c368aba2c29129e583830" FOREIGN KEY ("request_id") REFERENCES "requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "FK_458057fa75b66e68a275647da2e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "FK_458057fa75b66e68a275647da2e"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_405532c368aba2c29129e583830"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_b9e28779ec77ff2223e2da41f6d"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_640ed9849e6eb66177436f91f50"`);
        await queryRunner.query(`ALTER TABLE "process_steps" DROP CONSTRAINT "FK_a26849bc9154027c9600ca9aff5"`);
        await queryRunner.query(`ALTER TABLE "bank_account_owners" DROP CONSTRAINT "FK_baa295509b3588f4464c092b9c1"`);
        await queryRunner.query(`ALTER TABLE "bank_account_validators" DROP CONSTRAINT "FK_0e50563ece8cfec65958af9704b"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_d6c6be79cf7ccbbbe9bee93e91f"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_0d449eefabbcd1dcfcda92e188e"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_e336e481a84734861089a92a233"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP CONSTRAINT "FK_8fbbb57920b39f72929d57e88cc"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP CONSTRAINT "FK_158d12602ae023c7b33054fb54f"`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" DROP CONSTRAINT "FK_fe835abf385aade7c256ebcdc4c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "type" character varying NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "company"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`DROP TABLE "process_config"`);
        await queryRunner.query(`DROP TABLE "user_preferences"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TABLE "process_steps"`);
        await queryRunner.query(`DROP TABLE "bank_account_owners"`);
        await queryRunner.query(`DROP TABLE "bank_account_validators"`);
        await queryRunner.query(`DROP TABLE "members"`);
        await queryRunner.query(`DROP TABLE "requests"`);
        await queryRunner.query(`DROP TABLE "cuenta_bancaria_requests"`);
        await queryRunner.query(`DROP TABLE "renovacion_llc_requests"`);
        await queryRunner.query(`DROP TABLE "apertura_llc_requests"`);
    }

}
