import { MigrationInterface, QueryRunner } from "typeorm";

export class FixCheckRequestsStatusConstraint1767644446851 implements MigrationInterface {
    name = 'FixCheckRequestsStatusConstraint1767644446851'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "fk_clients_user"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "fk_clients_partner"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_client_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_partner_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_zoho_account_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_uuid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_members_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_unique_bank_validator"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bank_account_validators_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bank_account_owners_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_request_required_documents_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_process_steps_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_documents_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_documents_request_field"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_read"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_partner_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_email_partner_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_uuid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zoho_config_org_service"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zoho_config_region"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "check_user_type"`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" DROP CONSTRAINT "check_apertura_current_step"`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" DROP CONSTRAINT "check_apertura_llc_type"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP CONSTRAINT "check_renovacion_current_step"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP CONSTRAINT "check_renovacion_llc_type"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP CONSTRAINT "check_cuenta_current_step"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP CONSTRAINT "check_cuenta_llc_type"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "check_requests_type"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "check_requests_status"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "requests_status_check"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "check_member_percentage"`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" DROP CONSTRAINT "request_required_documents_request_type_check"`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" DROP CONSTRAINT "request_required_documents_llc_type_check"`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" DROP CONSTRAINT "request_required_documents_document_type_check"`);
        await queryRunner.query(`ALTER TABLE "process_steps" DROP CONSTRAINT "check_process_steps_status"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "check_documents_type"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "check_notifications_type"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "check_user_preferences_language"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "check_user_preferences_theme"`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" DROP COLUMN "display_order"`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ADD "order" integer NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."stage" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."work_drive_url_external" IS NULL`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ALTER COLUMN "required" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ALTER COLUMN "notifications" SET DEFAULT '{"email": true, "push": true, "requestUpdates": true, "documentUploads": true}'`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "zoho_config" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "zoho_config" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_7e22b4f1299bc243c47dfbbc09" ON "requests" ("uuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_189b0ac4aae6353359730759d9" ON "clients" ("uuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_b48860677afe62cd96e1265948" ON "clients" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_07a7a09b04e7b035c9d90cf498" ON "clients" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_628c0b2bd48412c961fe9f8e14" ON "clients" ("partner_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e90b64c966ad9d99429a410771" ON "zoho_config" ("org", "service") `);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_628c0b2bd48412c961fe9f8e149" FOREIGN KEY ("partner_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_07a7a09b04e7b035c9d90cf4984" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_07a7a09b04e7b035c9d90cf4984"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_628c0b2bd48412c961fe9f8e149"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e90b64c966ad9d99429a410771"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_628c0b2bd48412c961fe9f8e14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07a7a09b04e7b035c9d90cf498"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b48860677afe62cd96e1265948"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_189b0ac4aae6353359730759d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e22b4f1299bc243c47dfbbc09"`);
        await queryRunner.query(`ALTER TABLE "zoho_config" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "zoho_config" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ALTER COLUMN "notifications" SET DEFAULT '{"push": true, "email": true, "requestUpdates": true, "documentUploads": true}'`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ALTER COLUMN "required" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."work_drive_url_external" IS 'URL externa de Zoho WorkDrive desde Account'`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."stage" IS 'Etapa actual del blueprint de Zoho CRM'`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" DROP COLUMN "order"`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ADD "display_order" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "check_user_preferences_theme" CHECK (((theme)::text = ANY ((ARRAY['light'::character varying, 'dark'::character varying, 'auto'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "check_user_preferences_language" CHECK (((language)::text = ANY ((ARRAY['es'::character varying, 'en'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "check_notifications_type" CHECK (((type)::text = ANY ((ARRAY['info'::character varying, 'success'::character varying, 'warning'::character varying, 'error'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "check_documents_type" CHECK (((type)::text = ANY ((ARRAY['certificate'::character varying, 'document'::character varying, 'form'::character varying, 'other'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "process_steps" ADD CONSTRAINT "check_process_steps_status" CHECK (((status)::text = ANY ((ARRAY['completed'::character varying, 'current'::character varying, 'pending'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ADD CONSTRAINT "request_required_documents_document_type_check" CHECK (((document_type)::text = ANY ((ARRAY['certificate'::character varying, 'document'::character varying, 'form'::character varying, 'other'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ADD CONSTRAINT "request_required_documents_llc_type_check" CHECK (((llc_type)::text = ANY ((ARRAY['single'::character varying, 'multi'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "request_required_documents" ADD CONSTRAINT "request_required_documents_request_type_check" CHECK (((request_type)::text = ANY ((ARRAY['apertura-llc'::character varying, 'renovacion-llc'::character varying, 'cuenta-bancaria'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "check_member_percentage" CHECK (((percentage_of_participation >= (0)::numeric) AND (percentage_of_participation <= (100)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "requests_status_check" CHECK (((status)::text = ANY ((ARRAY['solicitud-recibida'::character varying, 'pendiente'::character varying, 'en-proceso'::character varying, 'completada'::character varying, 'rechazada'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "check_requests_status" CHECK (((status)::text = ANY ((ARRAY['pendiente'::character varying, 'en-proceso'::character varying, 'completada'::character varying, 'rechazada'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "check_requests_type" CHECK (((type)::text = ANY ((ARRAY['apertura-llc'::character varying, 'renovacion-llc'::character varying, 'cuenta-bancaria'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD CONSTRAINT "check_cuenta_llc_type" CHECK (((llc_type)::text = ANY ((ARRAY['single'::character varying, 'multi'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD CONSTRAINT "check_cuenta_current_step" CHECK (((current_step_number >= 1) AND (current_step_number <= 7)))`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD CONSTRAINT "check_renovacion_llc_type" CHECK (((llc_type)::text = ANY ((ARRAY['single'::character varying, 'multi'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD CONSTRAINT "check_renovacion_current_step" CHECK (((current_step_number >= 1) AND (current_step_number <= 6)))`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" ADD CONSTRAINT "check_apertura_llc_type" CHECK (((llc_type)::text = ANY ((ARRAY['single'::character varying, 'multi'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" ADD CONSTRAINT "check_apertura_current_step" CHECK (((current_step_number >= 1) AND (current_step_number <= 6)))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "check_user_type" CHECK (((type)::text = ANY ((ARRAY['user'::character varying, 'client'::character varying, 'partner'::character varying, 'admin'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_zoho_config_region" ON "zoho_config" ("region") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_zoho_config_org_service" ON "zoho_config" ("org", "service") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_clients_uuid" ON "clients" ("uuid") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_clients_email_partner_unique" ON "clients" ("partner_id", "email") WHERE (partner_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_clients_email" ON "clients" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_clients_user_id" ON "clients" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_clients_partner_id" ON "clients" ("partner_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_read" ON "notifications" ("user_id", "read") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_id" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_documents_request_field" ON "documents" ("request_id", "field_name") `);
        await queryRunner.query(`CREATE INDEX "idx_documents_request_id" ON "documents" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "idx_process_steps_request_id" ON "process_steps" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "idx_request_required_documents_type" ON "request_required_documents" ("request_type", "llc_type") `);
        await queryRunner.query(`CREATE INDEX "idx_bank_account_owners_request_id" ON "bank_account_owners" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "idx_bank_account_validators_request_id" ON "bank_account_validators" ("request_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_unique_bank_validator" ON "members" ("request_id") WHERE (validates_bank_account = true)`);
        await queryRunner.query(`CREATE INDEX "idx_members_request_id" ON "members" ("request_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_requests_uuid" ON "requests" ("uuid") `);
        await queryRunner.query(`CREATE INDEX "idx_requests_zoho_account_id" ON "requests" ("zoho_account_id") WHERE (zoho_account_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_requests_type" ON "requests" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_requests_status" ON "requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_requests_partner_id" ON "requests" ("partner_id") `);
        await queryRunner.query(`CREATE INDEX "idx_requests_client_id" ON "requests" ("client_id") `);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "fk_clients_partner" FOREIGN KEY ("partner_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "fk_clients_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
