import { MigrationInterface, QueryRunner } from "typeorm";

export class RemoveObsoleteFieldsFromRenovacionLlcRequests1769232394500 implements MigrationInterface {
    name = 'RemoveObsoleteFieldsFromRenovacionLlcRequests1769232394500'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "fk_clients_user"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "fk_clients_partner"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_requests_client_id_clients"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_partner_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_email_partner_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_clients_uuid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_client_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_partner_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_zoho_account_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_requests_uuid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_members_request_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_unique_bank_validator"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_read"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zoho_config_org_service"`);
        await queryRunner.query(`DROP INDEX "public"."idx_zoho_config_region"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "check_user_type"`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" DROP CONSTRAINT "check_apertura_current_step"`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" DROP CONSTRAINT "check_apertura_llc_type"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP CONSTRAINT "check_renovacion_current_step"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP CONSTRAINT "check_renovacion_llc_type"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP CONSTRAINT "check_cuenta_current_step"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP CONSTRAINT "check_cuenta_llc_type"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "check_requests_type"`);
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "check_requests_status"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "check_member_percentage"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "check_notifications_type"`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" DROP COLUMN "ein_number"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP COLUMN "data_is_correct"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP COLUMN "amount_to_pay"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP COLUMN "wants_invoice"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP COLUMN "observations"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP COLUMN "payment_method"`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" DROP COLUMN "payment_proof_url"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "is_registered_agent_in_usa"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "has_litigated_current_fiscal_year"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "is_same_address_as_business"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "accepts_terms_and_conditions"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "validator_use_email_for_relay_login"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "validator_can_receive_sms"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "validator_annual_income"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "registered_agent_name"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "registered_agent_address"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "swift_bic_aba"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "account_number"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "bank_account_type"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "litigation_details"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "document_certification"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "validator_citizenship"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "validator_title"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "validator_income_source"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "applicant_email"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "applicant_first_name"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "applicant_paternal_last_name"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "applicant_maternal_last_name"`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" DROP COLUMN "applicant_phone"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "emailVerificationToken"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "emailVerificationToken" character varying`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."stage" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."work_drive_url_external" IS NULL`);
        await queryRunner.query(`ALTER TABLE "requests" ALTER COLUMN "created_from" SET DEFAULT ''panel''`);
        await queryRunner.query(`ALTER TABLE "zoho_config" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "zoho_config" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_189b0ac4aae6353359730759d9" ON "clients" ("uuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_b48860677afe62cd96e1265948" ON "clients" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_07a7a09b04e7b035c9d90cf498" ON "clients" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_628c0b2bd48412c961fe9f8e14" ON "clients" ("partner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e22b4f1299bc243c47dfbbc09" ON "requests" ("uuid") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e90b64c966ad9d99429a410771" ON "zoho_config" ("org", "service") `);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_628c0b2bd48412c961fe9f8e149" FOREIGN KEY ("partner_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_07a7a09b04e7b035c9d90cf4984" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_e336e481a84734861089a92a233" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "requests" DROP CONSTRAINT "FK_e336e481a84734861089a92a233"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_07a7a09b04e7b035c9d90cf4984"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_628c0b2bd48412c961fe9f8e149"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e90b64c966ad9d99429a410771"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e22b4f1299bc243c47dfbbc09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_628c0b2bd48412c961fe9f8e14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07a7a09b04e7b035c9d90cf498"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b48860677afe62cd96e1265948"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_189b0ac4aae6353359730759d9"`);
        await queryRunner.query(`ALTER TABLE "zoho_config" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "zoho_config" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "requests" ALTER COLUMN "created_from" SET DEFAULT 'panel'`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."work_drive_url_external" IS 'URL externa de Zoho WorkDrive desde Account'`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."stage" IS 'Etapa actual del blueprint de Zoho CRM'`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "emailVerificationToken"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "emailVerificationToken" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "applicant_phone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "applicant_maternal_last_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "applicant_paternal_last_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "applicant_first_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "applicant_email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "validator_income_source" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "validator_title" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "validator_citizenship" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "document_certification" text`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "litigation_details" text`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "bank_account_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "account_number" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "swift_bic_aba" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "registered_agent_address" text`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "registered_agent_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "validator_annual_income" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "validator_can_receive_sms" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "validator_use_email_for_relay_login" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "accepts_terms_and_conditions" boolean`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "is_same_address_as_business" boolean`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "has_litigated_current_fiscal_year" boolean`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD "is_registered_agent_in_usa" boolean`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD "payment_proof_url" text`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD "payment_method" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD "observations" text`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD "wants_invoice" boolean`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD "amount_to_pay" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD "data_is_correct" boolean`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" ADD "ein_number" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "check_notifications_type" CHECK (((type)::text = ANY ((ARRAY['info'::character varying, 'success'::character varying, 'warning'::character varying, 'error'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "check_member_percentage" CHECK (((percentage_of_participation >= (0)::numeric) AND (percentage_of_participation <= (100)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "check_requests_status" CHECK (((status)::text = ANY ((ARRAY['solicitud-recibida'::character varying, 'pendiente'::character varying, 'en-proceso'::character varying, 'completada'::character varying, 'rechazada'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "check_requests_type" CHECK (((type)::text = ANY ((ARRAY['apertura-llc'::character varying, 'renovacion-llc'::character varying, 'cuenta-bancaria'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD CONSTRAINT "check_cuenta_llc_type" CHECK (((llc_type)::text = ANY ((ARRAY['single'::character varying, 'multi'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "cuenta_bancaria_requests" ADD CONSTRAINT "check_cuenta_current_step" CHECK (((current_step_number >= 1) AND (current_step_number <= 7)))`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD CONSTRAINT "check_renovacion_llc_type" CHECK (((llc_type)::text = ANY ((ARRAY['single'::character varying, 'multi'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "renovacion_llc_requests" ADD CONSTRAINT "check_renovacion_current_step" CHECK (((current_step_number >= 1) AND (current_step_number <= 6)))`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" ADD CONSTRAINT "check_apertura_llc_type" CHECK (((llc_type)::text = ANY ((ARRAY['single'::character varying, 'multi'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "apertura_llc_requests" ADD CONSTRAINT "check_apertura_current_step" CHECK (((current_step_number >= 1) AND (current_step_number <= 6)))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "check_user_type" CHECK (((type)::text = ANY ((ARRAY['user'::character varying, 'client'::character varying, 'partner'::character varying, 'admin'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_zoho_config_region" ON "zoho_config" ("region") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_zoho_config_org_service" ON "zoho_config" ("org", "service") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_read" ON "notifications" ("user_id", "read") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_id" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_unique_bank_validator" ON "members" ("request_id") WHERE (validates_bank_account = true)`);
        await queryRunner.query(`CREATE INDEX "idx_members_request_id" ON "members" ("request_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_requests_uuid" ON "requests" ("uuid") `);
        await queryRunner.query(`CREATE INDEX "idx_requests_zoho_account_id" ON "requests" ("zoho_account_id") WHERE (zoho_account_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_requests_type" ON "requests" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_requests_status" ON "requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_requests_partner_id" ON "requests" ("partner_id") `);
        await queryRunner.query(`CREATE INDEX "idx_requests_client_id" ON "requests" ("client_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_clients_uuid" ON "clients" ("uuid") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_clients_email_partner_unique" ON "clients" ("partner_id", "email") WHERE (partner_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_clients_email" ON "clients" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_clients_user_id" ON "clients" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_clients_partner_id" ON "clients" ("partner_id") `);
        await queryRunner.query(`ALTER TABLE "requests" ADD CONSTRAINT "FK_requests_client_id_clients" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "fk_clients_partner" FOREIGN KEY ("partner_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "fk_clients_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
