-- Generado por scripts/wxr-to-post-categories-sql.ts desde WordPress WXR
-- Crea categorías si no existen (slug); sincroniza nombre; enlaces post_categories por posts.slug
BEGIN;

INSERT INTO categories (name, slug, description, "createdAt", "updatedAt") SELECT 'Abrir LLC', 'abrir-llc', NULL, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.slug = 'abrir-llc');
UPDATE categories SET name = 'Abrir LLC', "updatedAt" = NOW() WHERE slug = 'abrir-llc';
INSERT INTO categories (name, slug, description, "createdAt", "updatedAt") SELECT 'Corporation', 'corporation', NULL, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.slug = 'corporation');
UPDATE categories SET name = 'Corporation', "updatedAt" = NOW() WHERE slug = 'corporation';
INSERT INTO categories (name, slug, description, "createdAt", "updatedAt") SELECT 'Costos LLC', 'costos-llc', NULL, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.slug = 'costos-llc');
UPDATE categories SET name = 'Costos LLC', "updatedAt" = NOW() WHERE slug = 'costos-llc';
INSERT INTO categories (name, slug, description, "createdAt", "updatedAt") SELECT 'Impuestos', 'impuestos', NULL, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.slug = 'impuestos');
UPDATE categories SET name = 'Impuestos', "updatedAt" = NOW() WHERE slug = 'impuestos';
INSERT INTO categories (name, slug, description, "createdAt", "updatedAt") SELECT 'Uncategorized', 'uncategorized', NULL, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.slug = 'uncategorized');
UPDATE categories SET name = 'Uncategorized', "updatedAt" = NOW() WHERE slug = 'uncategorized';

INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = '8-mejores-servicios-de-formacion-de-llc-en-estados-unidos' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'corporation' WHERE p.slug = 'abrir-corporacion' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'abrir-tu-llc-en-estados-unidos-desde-espana' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'abrir-una-llc-desde-espana' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'acuerdo-operativo-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'articles-of-organization-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'corporation' WHERE p.slug = 'c-corp-vs-s-corp' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-abrir-una-corporacion-en-florida' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-abrir-una-llc-desde-argentina' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-abrir-una-llc-en-california' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-abrir-una-llc-en-delaware' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-abrir-una-llc-en-florida' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-abrir-una-llc-en-georgia' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-abrir-una-llc-en-texas' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-abrir-una-llc-en-wyoming' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-abrir-una-llc-new-mexico' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-abrir-una-llc-no-residente' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-disolver-una-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-elegir-el-nombre-de-mi-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'como-renovar-mi-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'corporacion-vs-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'corporation' WHERE p.slug = 'corporacion-vs-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'costos-llc' WHERE p.slug = 'costo-abrir-una-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'costos-llc' WHERE p.slug = 'costo-llc-delaware' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'costos-llc' WHERE p.slug = 'costo-llc-florida' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'impuestos' WHERE p.slug = 'declarar-impuestos-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'uncategorized' WHERE p.slug = 'diferentes-tipos-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'en-que-estado-registrar-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'impuestos' WHERE p.slug = 'impuestos-llc-delaware' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'impuestos' WHERE p.slug = 'impuestos-llc-florida' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'llc-freelance' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'llc-para-ecommerce' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'llc-para-trading' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'llc-unipersonal' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'llc-vs-estonian-ou-que-estructura-le-conviene-mas-a-tu-negocio' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'llc-vs-sole-proprietorship' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'mejores-cuentas-bancarias-empresariales-para-no-residentes' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'mejores-servicios-agente-registrado' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'opinion-de-dasbank-vale-la-pena' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'opinion-de-defentux' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'opinion-de-globalfy' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'opinion-firmaway' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'opinion-legalzoom' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'que-es-agente-registrado' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'corporation' WHERE p.slug = 'que-es-agente-registrado' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'corporation' WHERE p.slug = 'que-es-corporacion' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'que-es-dba' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'que-es-ein-number-y-para-que-sirve' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'impuestos' WHERE p.slug = 'que-es-ein-number-y-para-que-sirve' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'impuestos' WHERE p.slug = 'que-es-etbus' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'que-es-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'impuestos' WHERE p.slug = 'que-impuestos-paga-una-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'reporte-boi' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'corporation' WHERE p.slug = 's-corp' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'impuestos' WHERE p.slug = 'ssn-itin-tax-id-ein-diferencias' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'usos-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'ventajas-llc-florida' ON CONFLICT ("post_id", "category_id") DO NOTHING;
INSERT INTO post_categories ("post_id", "category_id") SELECT p.id, c.id FROM posts p JOIN categories c ON c.slug = 'abrir-llc' WHERE p.slug = 'ventajas-llc' ON CONFLICT ("post_id", "category_id") DO NOTHING;

COMMIT;
